# Lab 4 tasks


In [1]:
import numpy as np

## Create a nd array of size 3 x 3 x 3 and perform subtraction operation as per x axis, y axis and z axis.

In [29]:
array = np.array([[[1,2,3],
[4,5,6],
[7,8, -9]],
[[10,11,12],
[13,14,15],
[16,-17,18]],
[[-19,20,21],
[22,23,24],
[24,25,26]]])

x_diff = np.diff(array, axis=0)
y_diff = np.diff(array, axis=1)
z_diff = np.diff(array, axis=2)

print(f"The original array is:\n {array}\n")
print(f"The difference along the x-axis is:\n {x_diff}\n")
print(f"The difference along the y-axis is:\n {y_diff}\n")
print(f"The difference along the z-axis is:\n {z_diff}")

The original array is:
 [[[  1   2   3]
  [  4   5   6]
  [  7   8  -9]]

 [[ 10  11  12]
  [ 13  14  15]
  [ 16 -17  18]]

 [[-19  20  21]
  [ 22  23  24]
  [ 24  25  26]]]

The difference along the x-axis is:
 [[[  9   9   9]
  [  9   9   9]
  [  9 -25  27]]

 [[-29   9   9]
  [  9   9   9]
  [  8  42   8]]]

The difference along the y-axis is:
 [[[  3   3   3]
  [  3   3 -15]]

 [[  3   3   3]
  [  3 -31   3]]

 [[ 41   3   3]
  [  2   2   2]]]

The difference along the z-axis is:
 [[[  1   1]
  [  1   1]
  [  1 -17]]

 [[  1   1]
  [  1   1]
  [-33  35]]

 [[ 39   1]
  [  1   1]
  [  1   1]]]


## 2. Demonstrate the following on the above created nd array:

### basic indexing

In [3]:
new_arr = array.shape

new_arr = np.arange(27).reshape(new_arr)
print(new_arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [4]:
array[1, -1]

array([ 16, -17,  18])

### slicing

In [5]:
print(array[1:2:1])

[[[ 10  11  12]
  [ 13  14  15]
  [ 16 -17  18]]]


In [6]:
print(array[1:])

[[[ 10  11  12]
  [ 13  14  15]
  [ 16 -17  18]]

 [[-19  20  21]
  [ 22  23  24]
  [ 24  25  26]]]


### boolean indexing

In [7]:
# select all entries from an array which are not NaN:
new_array = np.array(array)
new_array[~np.isnan(new_array)]

array([  1,   2,   3,   4,   5,   6,   7,   8,  -9,  10,  11,  12,  13,
        14,  15,  16, -17,  18, -19,  20,  21,  22,  23,  24,  24,  25,
        26])

In [8]:
# add a constant to all negative elements:
new_array = np.array(array)
new_array[new_array < 0] += 20
new_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 11]],

       [[10, 11, 12],
        [13, 14, 15],
        [16,  3, 18]],

       [[ 1, 20, 21],
        [22, 23, 24],
        [24, 25, 26]]])

### fancy indexing

In [9]:
import numpy as np 
indices = np.array([0,2,1])
result = array[:, indices]
print(f"The original array is:\n {array}")
print(f"The resultant array is:\n {result}")

The original array is:
 [[[  1   2   3]
  [  4   5   6]
  [  7   8  -9]]

 [[ 10  11  12]
  [ 13  14  15]
  [ 16 -17  18]]

 [[-19  20  21]
  [ 22  23  24]
  [ 24  25  26]]]
The resultant array is:
 [[[  1   2   3]
  [  7   8  -9]
  [  4   5   6]]

 [[ 10  11  12]
  [ 16 -17  18]
  [ 13  14  15]]

 [[-19  20  21]
  [ 24  25  26]
  [ 22  23  24]]]


In [10]:
import numpy as np

# create an index array of shape (3, 2) with random values
indices = np.random.randint(0, 3, size=(3, 2))

# use the index array to select elements from the original array
result = array[indices[:, 0], :, indices[:, 1]]

# print the original and resulting arrays
print("Original array:\n", array)
print("Index array:\n", indices)
print("Resulting array:\n", result)


Original array:
 [[[  1   2   3]
  [  4   5   6]
  [  7   8  -9]]

 [[ 10  11  12]
  [ 13  14  15]
  [ 16 -17  18]]

 [[-19  20  21]
  [ 22  23  24]
  [ 24  25  26]]]
Index array:
 [[2 1]
 [1 0]
 [1 1]]
Resulting array:
 [[ 20  23  25]
 [ 10  13  16]
 [ 11  14 -17]]


## 3. Demonstrate the use of the following universal functions

### Trigonometric functions

In [11]:
import numpy as np
angles = np.array([0,30,40,60,90,120,180])
radians = np.deg2rad(angles)
print('Sine of angles:') # Sine
sine_value = np.sin(radians)
print(np.sin(radians))

Sine of angles:
[0.00000000e+00 5.00000000e-01 6.42787610e-01 8.66025404e-01
 1.00000000e+00 8.66025404e-01 1.22464680e-16]


In [12]:
print('Inverse Sine:') # Inverse sine
print(np.rad2deg(np.arcsin(sine_value)))

Inverse Sine:
[0.0000000e+00 3.0000000e+01 4.0000000e+01 6.0000000e+01 9.0000000e+01
 6.0000000e+01 7.0167093e-15]


In [13]:
print('Sine hyperbolic of angles:') #Hyperbolic
sineh_value = np.sinh(radians)
print(np.sinh(radians))


Sine hyperbolic of angles:
[ 0.          0.54785347  0.75623999  1.24936705  2.3012989   3.99869134
 11.54873936]


### Statistical Functions

In [14]:
import random
random_array = np.array(random.sample(range(0, 101), 10))

print(random_array)


[29 15 33  2 78 34 62 98 36 32]


##### Min and Max

In [15]:
print(f"The minimum element in the array is: {np.amin(random_array)}, and the maximum element is: {np.amax(random_array)}")

The minimum element in the array is: 2, and the maximum element is: 98


##### Standard deviation (how spread out the values are from the mean)

In [16]:
print(f"The Standard deviation of the array is: {np.std(random_array)}")

The Standard deviation of the array is: 27.587859648765797


### Bit-Twiddling Functions

In [17]:
import numpy as np
import random

a1 = np.array(random.sample(range(0,20,2),10))
a2 = np.array(random.sample(range(1,22,2),10))

print(a1,a2)

[12 10  6  2 18  0 14 16  8  4] [ 7 13  5 11 21 19  9 15  3  1]


##### bitwise xor

In [18]:
print(f"The bitwise xor of a1 and a2 is: {np.bitwise_xor(a1,a2)}")

The bitwise xor of a1 and a2 is: [11  7  3  9  7 19  7 31 11  5]


##### Right shift

In [19]:
print(f"The right shift of a1 and a2 is: {np.right_shift(a1,a2)}")

The right shift of a1 and a2 is: [0 0 0 0 0 0 0 0 1 2]


## 4. Download the dataset of your choice and demonstrate the following operations on it: 

#### 1. Reading csv as an array

In [20]:
import pandas as pd
import csv 

# df = pd.read_csv("C:\\Users\\Ananya\\OneDrive\\Projects and Labs\\DAV Lab\\Lab4\\archive\\seattle-weather.csv")
weather = np.genfromtxt("seattle-weather.csv", delimiter=",", skip_header=1)
print(weather)


[[ nan  0.  12.8  5.   4.7  nan]
 [ nan 10.9 10.6  2.8  4.5  nan]
 [ nan  0.8 11.7  7.2  2.3  nan]
 ...
 [ nan  0.   7.2  0.6  2.6  nan]
 [ nan  0.   5.6 -1.   3.4  nan]
 [ nan  0.   5.6 -2.1  3.5  nan]]


#### 2. Performing nd operations

In [21]:
# Reshaping
print(weather.shape)
new_a = weather.reshape(6, 1461)
print(new_a.shape)

(1461, 6)
(6, 1461)


In [22]:
# Ravel - turn an array into one dimensional representation
new_a.ravel()


array([ nan,  0. , 12.8, ..., -2.1,  3.5,  nan])

In [23]:
# Transpose
new_a.transpose()

array([[ nan, 10.6,  nan,  5. ,  nan,  7.8],
       [ 0. ,  2.9,  0. ,  1.7,  0. ,  3.7],
       [12.8,  nan, 20.6,  nan, 23.3,  nan],
       ...,
       [ nan,  3.3,  nan, 13.9,  nan, -2.1],
       [ 0. ,  3.1,  0.5,  1.9,  0. ,  3.5],
       [22.2,  nan,  8.3,  nan, 18.3,  nan]])

In [24]:
# vstack - to combine two datasets and display the shape of the result
dataset = np.genfromtxt("cleaned_dataset.csv", delimiter=",", skip_header=1)
new = dataset.reshape(100,6)

print(weather.shape, new.shape)
stack = np.vstack((weather, new))
stack.shape



(1461, 6) (100, 6)


(1561, 6)

In [25]:
# Concatenate - to concatenate two arrays along an axis
np.concatenate((weather, new), axis=0)


array([[            nan,  0.00000000e+00,  1.28000000e+01,
         5.00000000e+00,  4.70000000e+00,             nan],
       [            nan,  1.09000000e+01,  1.06000000e+01,
         2.80000000e+00,  4.50000000e+00,             nan],
       [            nan,  8.00000000e-01,  1.17000000e+01,
         7.20000000e+00,  2.30000000e+00,             nan],
       ...,
       [-6.20200000e+00,  0.00000000e+00,  6.53000000e-02,
         1.29008000e+02,  9.73000000e-01,             nan],
       [ 4.90000000e+01,  1.83000000e-01,  5.76888000e+05,
         9.57000000e-01,  9.26884753e-02,  3.00000000e+00],
       [-7.76750000e+00,  1.00000000e+00,  6.89000000e-02,
         1.06714000e+02,  9.30000000e-01,             nan]])

## 5. Perform file input and output operations on nd array using save, load, savetxt and loadtxt methods.


In [26]:
array

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,  -9]],

       [[ 10,  11,  12],
        [ 13,  14,  15],
        [ 16, -17,  18]],

       [[-19,  20,  21],
        [ 22,  23,  24],
        [ 24,  25,  26]]])

#### Save and load

In [27]:
np.save('save', array)
b = np.load('save.npy')
b

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,  -9]],

       [[ 10,  11,  12],
        [ 13,  14,  15],
        [ 16, -17,  18]],

       [[-19,  20,  21],
        [ 22,  23,  24],
        [ 24,  25,  26]]])

#### savetxt and loadtxt

In [28]:
np.savetxt('savetxt.txt', array.ravel())
b = np.loadtxt('savetxt.txt')
b

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,  -9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16., -17.,  18., -19.,  20.,  21.,  22.,
        23.,  24.,  24.,  25.,  26.])